/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.ticket.booking;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Damilare Asuni
 */
public class welcomePage extends javax.swing.JFrame {

    /**
     * Creates new form welcomePage
     */
    public welcomePage() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/ticket/booking/vray_vehicle_bus.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-130, 60, 1510, 510);

        jLabel3.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        jLabel3.setText("lag bus ticketing and reservation system");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 0, 330, 80);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(100, 580, 100, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(100, 630, 100, 30);

        jLabel1.setText("UserName");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 580, 70, 30);

        jLabel4.setText("PassWord");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 630, 70, 30);

        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 670, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
                                           
        try {
            String usernameEntered = jTextField1.getText().trim();
            String passwordEntered = jTextField2.getText().trim();
            boolean verify=true;
            try ( //Create a connection to the database
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/busreservation", "root","")) {
                Statement st = (Statement) con.createStatement();
                ResultSet res = st.executeQuery("SELECT * FROM  stafflogin");
                //select the items in the database table one after the other
                while (res.next()) {
                    String usernameStored= res.getString("Username").trim();
                    String passwordStored = res.getString("Password").trim();
                    
                    if ((usernameEntered.equals(usernameStored)) && (passwordEntered.equals(passwordStored)))
                    {
                        verify=true;
                        break;
                    }
                    else
                    {
                        verify=false;
                    }
                }
                if (verify==true)
                {
                    this.setVisible(false);
                    MakeReservation newMakeReservation = new MakeReservation();
                    newMakeReservation.setVisible(true);
                }
                else
                {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null, " Invalid Details");
                    
                    
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MakeReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                  

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}

